version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres4351
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"

  web:
    build: .
    command: [ "/wait-for-it.sh", "db:5432", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    working_dir: /app/src
    container_name: fastapi
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres4351@db:5432/app_db
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
